// Activity Feed Hook
// src/hooks/useActivityFeed.ts

import { useState, useCallback, useMemo } from 'react';
import { useFocusEffect } from '@react-navigation/native';
import { activity } from '../services/api/index';
import { useAppSelector } from './useStore';
import type { ActionLogEntry } from '../types';
import { getErrorMessage } from '../utils/errorUtils';
import { DEMO_TOKEN } from '../constants/business';

interface UseActivityFeedResult {
  activities: ActionLogEntry[];
  isLoading: boolean;
  isRefreshing: boolean;
  error: string | null;
  hasMore: boolean;
  refresh: () => Promise<void>;
  loadMore: () => Promise<void>;
}

export function useActivityFeed(initialLimit = 10): UseActivityFeedResult {
  const [activities, setActivities] = useState<ActionLogEntry[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [hasMore, setHasMore] = useState(false);
  const [cursor, setCursor] = useState<string | undefined>(undefined);

  // Check if we're in demo mode (runtime check via Redux)
  const authToken = useAppSelector((state) => state.auth.authToken);
  const reduxActionLog = useAppSelector((state) => state.portfolio.actionLog);
  const isDemoMode = authToken === DEMO_TOKEN;

  // Demo mode activities from Redux state
  const demoActivities = useMemo(() => {
    if (!isDemoMode) return [];
    return (reduxActionLog || []).slice(0, initialLimit);
  }, [isDemoMode, reduxActionLog, initialLimit]);

  const fetchActivities = useCallback(async (isRefresh = false) => {
    // In demo mode, use Redux state instead of API
    if (isDemoMode) {
      setActivities(demoActivities);
      setHasMore(false);
      setIsLoading(false);
      setIsRefreshing(false);
      return;
    }

    try {
      if (isRefresh) {
        setIsRefreshing(true);
      } else if (activities.length === 0) {
        setIsLoading(true);
      }
      setError(null);

      const response = await activity.getRecent(initialLimit);
      // Map backend field names to frontend expected names (fallback for any field mismatches)
      // BUG-3 FIX: Ensure all required fields are populated for display
      const mappedActivities = (response?.activities || []).map((a: any) => ({
        ...a,
        type: a.type || a.actionType || 'UNKNOWN',  // Support both field names, default to UNKNOWN
        timestamp: a.timestamp || a.createdAt || new Date().toISOString(),  // Default to now
        amountIRR: a.amountIRR ?? a.amountIrr ?? 0,  // Support both field names
        message: a.message || '',  // Ensure message field exists (will be generated by formatActivityMessage)
        boundary: a.boundary || 'SAFE',  // Default boundary
      }));
      setActivities(mappedActivities);
      setHasMore(response?.hasMore || false);
      setCursor(response?.nextCursor);
    } catch (err) {
      setError(getErrorMessage(err, 'Failed to load activities'));
    } finally {
      setIsLoading(false);
      setIsRefreshing(false);
    }
  }, [initialLimit, isDemoMode, demoActivities]);

  const loadMore = useCallback(async () => {
    // No pagination in demo mode
    if (isDemoMode) return;
    if (!hasMore || isLoading || !cursor) return;

    try {
      const response = await activity.getAll(cursor);
      // Map backend field names to frontend expected names
      // BUG-3 FIX: Ensure all required fields are populated
      const mappedActivities = (response?.activities || []).map((a: any) => ({
        ...a,
        type: a.type || a.actionType || 'UNKNOWN',
        timestamp: a.timestamp || a.createdAt || new Date().toISOString(),
        amountIRR: a.amountIRR ?? a.amountIrr ?? 0,
        message: a.message || '',
        boundary: a.boundary || 'SAFE',
      }));
      setActivities((prev) => [...prev, ...mappedActivities]);
      setHasMore(response.hasMore);
      setCursor(response.nextCursor);
    } catch (err) {
      setError(getErrorMessage(err, 'Failed to load more activities'));
    }
  }, [hasMore, isLoading, cursor, isDemoMode]);

  const refresh = useCallback(async () => {
    await fetchActivities(true);
  }, [fetchActivities]);

  // Fetch on screen focus
  useFocusEffect(
    useCallback(() => {
      fetchActivities();
    }, [fetchActivities])
  );

  return {
    activities: isDemoMode ? demoActivities : activities,
    isLoading: isDemoMode ? false : isLoading,
    isRefreshing,
    error,
    hasMore: isDemoMode ? false : hasMore,
    refresh,
    loadMore,
  };
}

export default useActivityFeed;
